/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CostEstimatorRouteImport } from './routes/cost-estimator'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesSlugRouteImport } from './routes/venues.$slug'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated.owner'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CostEstimatorRoute = CostEstimatorRouteImport.update({
  id: '/cost-estimator',
  path: '/cost-estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesSlugRoute = VenuesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VenuesRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cost-estimator': typeof CostEstimatorRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/venues': typeof VenuesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/venues/$slug': typeof VenuesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cost-estimator': typeof CostEstimatorRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/venues': typeof VenuesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/venues/$slug': typeof VenuesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cost-estimator': typeof CostEstimatorRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/venues': typeof VenuesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/venues/$slug': typeof VenuesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cost-estimator'
    | '/login'
    | '/signup'
    | '/venues'
    | '/dashboard'
    | '/owner'
    | '/venues/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cost-estimator'
    | '/login'
    | '/signup'
    | '/venues'
    | '/dashboard'
    | '/owner'
    | '/venues/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cost-estimator'
    | '/login'
    | '/signup'
    | '/venues'
    | '/_authenticated/dashboard'
    | '/_authenticated/owner'
    | '/venues/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CostEstimatorRoute: typeof CostEstimatorRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VenuesRoute: typeof VenuesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-estimator': {
      id: '/cost-estimator'
      path: '/cost-estimator'
      fullPath: '/cost-estimator'
      preLoaderRoute: typeof CostEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$slug': {
      id: '/venues/$slug'
      path: '/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof VenuesSlugRouteImport
      parentRoute: typeof VenuesRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface VenuesRouteChildren {
  VenuesSlugRoute: typeof VenuesSlugRoute
}

const VenuesRouteChildren: VenuesRouteChildren = {
  VenuesSlugRoute: VenuesSlugRoute,
}

const VenuesRouteWithChildren =
  VenuesRoute._addFileChildren(VenuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CostEstimatorRoute: CostEstimatorRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VenuesRoute: VenuesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
